# Jekyll の基本設定
title: "Minecraft Blog"
description: "マイクラブログ"
# テーマ
theme: minima
# ページネーション設定
plugins:
  - jekyll-paginate
paginate: 5
paginate_path: "/page:num"

# Markdown の拡張
markdown: kramdown

# 既存設定...
baseurl: "/minecraft-blog"   # リポジトリ名を設定

# posts フォルダ内のファイルは自動で layout: post を適用
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: post
